config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index]
  authenticated :user do
    root to: "static_page#index"
  end
  unauthenticated :user do
    root to: "homes#index"
  end
  resources :static_page, only: [:new, :create]
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  resources :paymentin, only: [:index]
  resources :paymentout, only: [:index]
  resources :memory_sale, only: [:destroy]
  resources :memory, only: [:destroy]
  resources :purshas
  resources :sales
  resources :receipts, only: [:index]
  resources :paymentsuppliers
  resources :payments
  resources :stockcurrents
  resources :stocklevels
  resources :stockins
  resources :ticketlines
  resources :tickets
  resources :closedcashes
  resources :screens
  resources :rolepermissions
  resources :roles
  resources :employees
  resources :customers
  resources :suppliers
  resources :typeproducts
  resources :categories
  resources :products
  resources :businesslines
  resources :branches
  resources :companies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/typeproduct.rb
class Typeproduct < ApplicationRecord
    belongs_to :product, optional: true
     
end

app/controllers/typeproducts_controller.rb
class TypeproductsController < ApplicationController
  before_action :set_typeproduct, only: [:show, :edit, :update, :destroy]

  # GET /typeproducts
  # GET /typeproducts.json
  def index
    @typeproducts = Typeproduct.all
  end

  # GET /typeproducts/1
  # GET /typeproducts/1.json
  def show
  end

  # GET /typeproducts/new
  def new
    @typeproduct = Typeproduct.new
  end

  # GET /typeproducts/1/edit
  def edit
  end

  # POST /typeproducts
  # POST /typeproducts.json
  def create
    @typeproduct = Typeproduct.new(typeproduct_params)

    respond_to do |format|
      if @typeproduct.save
        format.html { redirect_to @typeproduct, notice: 'Typeproduct was successfully created.' }
        format.json { render :show, status: :created, location: @typeproduct }
      else
        format.html { render :new }
        format.json { render json: @typeproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /typeproducts/1
  # PATCH/PUT /typeproducts/1.json
  def update
    respond_to do |format|
      if @typeproduct.update(typeproduct_params)
        format.html { redirect_to @typeproduct, notice: 'Typeproduct was successfully updated.' }
        format.json { render :show, status: :ok, location: @typeproduct }
      else
        format.html { render :edit }
        format.json { render json: @typeproduct.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /typeproducts/1
  # DELETE /typeproducts/1.json
  def destroy
    @typeproduct.destroy
    respond_to do |format|
      format.html { redirect_to typeproducts_url, notice: 'Typeproduct was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_typeproduct
      @typeproduct = Typeproduct.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def typeproduct_params
      params.require(:typeproduct).permit(:line)
    end
end

app/helpers/typeproducts_helper.rb
module TypeproductsHelper
end

app/views/typeproducts/_form.html.erb
<%= form_with(model: typeproduct, local: true) do |form| %>
  <% if typeproduct.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(typeproduct.errors.count, "error") %> prohibited this typeproduct from being saved:</h2>

      <ul>
      <% typeproduct.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :line %>
    <%= form.text_field :line %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/typeproducts/edit.html.erb
<h1>Editing Typeproduct</h1>

<%= render 'form', typeproduct: @typeproduct %>

<%= link_to 'Show', @typeproduct %> |
<%= link_to 'Back', typeproducts_path %>

app/views/typeproducts/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Typeproducts</h1>

<table>
  <thead>
    <tr>
      <th>Line</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @typeproducts.each do |typeproduct| %>
      <tr>
        <td><%= typeproduct.line %></td>
        <td><%= link_to 'Show', typeproduct %></td>
        <td><%= link_to 'Edit', edit_typeproduct_path(typeproduct) %></td>
        <td><%= link_to 'Destroy', typeproduct, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Typeproduct', new_typeproduct_path %>

app/views/typeproducts/new.html.erb
<h1>New Typeproduct</h1>

<%= render 'form', typeproduct: @typeproduct %>

<%= link_to 'Back', typeproducts_path %>

app/views/typeproducts/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Line:</strong>
  <%= @typeproduct.line %>
</p>

<%= link_to 'Edit', edit_typeproduct_path(@typeproduct) %> |
<%= link_to 'Back', typeproducts_path %>