config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index]
  authenticated :user do
    root to: "static_page#index"
  end
  unauthenticated :user do
    root to: "homes#index"
  end
  resources :static_page, only: [:new, :create]
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  resources :paymentin, only: [:index]
  resources :paymentout, only: [:index]
  resources :memory_sale, only: [:destroy]
  resources :memory, only: [:destroy]
  resources :purshas
  resources :sales
  resources :receipts, only: [:index]
  resources :paymentsuppliers
  resources :payments
  resources :stockcurrents
  resources :stocklevels
  resources :stockins
  resources :ticketlines
  resources :tickets
  resources :closedcashes
  resources :screens
  resources :rolepermissions
  resources :roles
  resources :employees
  resources :customers
  resources :suppliers
  resources :typeproducts
  resources :categories
  resources :products
  resources :businesslines
  resources :branches
  resources :companies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
    belongs_to :receipt
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:discountPer, :discountVal, :payment, :total, :transid)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<%= form_with(model: payment, local: true) do |form| %>
  <% if payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
      <% payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :discountPer %>
    <%= form.text_field :discountPer %>
  </div>

  <div class="field">
    <%= form.label :discountVal %>
    <%= form.text_field :discountVal %>
  </div>

  <div class="field">
    <%= form.label :payment %>
    <%= form.text_field :payment %>
  </div>

  <div class="field">
    <%= form.label :total %>
    <%= form.text_field :total %>
  </div>

  <div class="field">
    <%= form.label :transid %>
    <%= form.text_field :transid %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/payments/edit.html.erb
<h1>Editing Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Show', @payment %> |
<%= link_to 'Back', payments_path %>

app/views/payments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Payments</h1>

<table>
  <thead>
    <tr>
      <th>Discountper</th>
      <th>Discountval</th>
      <th>Payment</th>
      <th>Total</th>
      <th>Transid</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= payment.discountPer %></td>
        <td><%= payment.discountVal %></td>
        <td><%= payment.payment %></td>
        <td><%= payment.total %></td>
        <td><%= payment.transid %></td>
        <td><%= link_to 'Show', payment %></td>
        <td><%= link_to 'Edit', edit_payment_path(payment) %></td>
        <td><%= link_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Payment', new_payment_path %>

app/views/payments/new.html.erb
<h1>New Payment</h1>

<%= render 'form', payment: @payment %>

<%= link_to 'Back', payments_path %>

app/views/payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Discountper:</strong>
  <%= @payment.discountPer %>
</p>

<p>
  <strong>Discountval:</strong>
  <%= @payment.discountVal %>
</p>

<p>
  <strong>Payment:</strong>
  <%= @payment.payment %>
</p>

<p>
  <strong>Total:</strong>
  <%= @payment.total %>
</p>

<p>
  <strong>Transid:</strong>
  <%= @payment.transid %>
</p>

<%= link_to 'Edit', edit_payment_path(@payment) %> |
<%= link_to 'Back', payments_path %>