config/routes.rb
Rails.application.routes.draw do
  resources :homes, only: [:index]
  authenticated :user do
    root to: "static_page#index"
  end
  unauthenticated :user do
    root to: "homes#index"
  end
  resources :static_page, only: [:new, :create]
  devise_for :users, controllers: { registrations: "registrations" }
  resources :users, only: [:show]
  resources :paymentin, only: [:index]
  resources :paymentout, only: [:index]
  resources :memory_sale, only: [:destroy]
  resources :memory, only: [:destroy]
  resources :purshas
  resources :sales
  resources :receipts, only: [:index]
  resources :paymentsuppliers
  resources :payments
  resources :stockcurrents
  resources :stocklevels
  resources :stockins
  resources :ticketlines
  resources :tickets
  resources :closedcashes
  resources :screens
  resources :rolepermissions
  resources :roles
  resources :employees
  resources :customers
  resources :suppliers
  resources :typeproducts
  resources :categories
  resources :products
  resources :businesslines
  resources :branches
  resources :companies

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/sales_controller.rb
class SalesController < ApplicationController
  before_action -> { as_access?("Sales") }

  def index
    @categories = current_user.company.categories.all
    @memory = current_user.memory_sale
    @globalprice = 0
    current_user.memory_sale.ticketlines.each do |ticketline|
      @globalprice += ticketline.product.pricesell.to_i * ticketline.units.to_i
    end
  end

  def new
    @categories = current_user.company.categories.all
    @category = Category.find(params[:category_id])
    respond_to do |format|
      format.html { redirect_to new_pursha_path}
      format.js {}
    end
  end

  def create
    @product = Product.find(params[:product_id])
    @already_here = false
    current_user.memory_sale.ticketlines.each do |ticketline|
      if ticketline.product.name == @product.name
        @already_here = true
        ticketline.update(units: ticketline.units + 1)
      end
    end
    @already_here == false ? Ticketline.create(memory_sale: current_user.memory_sale, product: @product) : 0
    respond_to do |format|
      format.html { redirect_to purshas_path}
      format.js {}
    end
  end
end

app/helpers/sales_helper.rb
module SalesHelper
end

app/views/sales/_card_categories.html.erb
<%= link_to sales_path, class: 'col-xl-3 col-md-6 mb-4', style: 'cursor: pointer;', data: { remote: true, params: {:category_id => category.id}.to_param} do %>
  <div class="card border-left-primary shadow h-100 py-2">
    <div class="card-body">
      <div class="row no-gutters align-items-center">
        <div class="col mr-2">
          <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><%= category.name %></div>
          <div class="h5 mb-0 font-weight-bold text-gray-800"><%= category.products.length %> types of products</div>
        </div>
        <div class="col-auto">
          <i class="fas fa-folder fa-2x text-gray-300"></i>
        </div>
      </div>
    </div>
  </div>
<% end %>

app/views/sales/_card_products.html.erb
<h1 class="h3 mb-2 text-gray-800">Products of <%= category.name %></h1><br>
<div class="row">
<% category.products.each do |product| %>
  <%= link_to sales_path, id: "link-card-product",class: 'col-xl-3 col-md-6 mb-4', style: 'cursor: pointer;', data: { method: :post, remote: true, params: {:product_id => product.id}.to_param} do %>
    <div class="card border-left-warning shadow h-100 py-2">
      <div class="card-body">
        <div class="row no-gutters align-items-center">
          <div class="col mr-2">
            <div class="text-xs font-weight-bold text-primary text-uppercase mb-1"><%= product.name %></div>
            <div class="mb-0 font-weight-bold text-gray-800">quantity : <span id="quantity-<%=product.id%>"><%= product.stockvolume %><span></div>
          </div>
          <div class="col-auto">
            <i class="fas fa-calendar fa-2x text-gray-300"></i>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>
</div>

app/views/sales/create.js.erb
var table = document.getElementById('table')
table.insertAdjacentHTML('afterbegin', '<tr><td><%= @product.id %></td><td><%= @product.name %></td><td><span id="<%=@product.id%>"><%= @product.pricesell %></span> €</td><td>1</td></tr>');
var productPrice = parseInt(document.getElementById('<%=@product.id%>').innerHTML);
var globalPrice = parseInt(document.getElementById('globalprice').innerHTML);
document.getElementById('globalprice').innerHTML = globalPrice + productPrice;

app/views/sales/index.html.erb
<h1 class="h3 mb-2 text-gray-800">Categories</h1>

<div class="row" id="categories">
  <% @categories.each do |category|%>
    <%= render 'card_categories', category: category, ticket: @ticket %>
  <% end %>
</div>

<div id="products">
</div>

  <div class="card shadow mb-4">
    <div class="card-header py-3">
      <h6>Receipt</h6>
    </div>
    <div class="card-body">
      <div class="table-responsive">
        <table class="table table-bordered" id="dataTable" width="100%" cellspacing="0">
          <thead>
            <tr>
              <th>#</th>
              <th>Product</th>
              <th>Price</th>
              <th>Quantity</th>
            </tr>
          </thead>
          <tbody id="table">
              <% @memory.ticketlines.each do |ticketline| %>
              <tr>
                <td><%= ticketline.product.id %></td>
                <td><%= ticketline.product.name %></td>
                <td id="<%= ticketline.product.id %>"><%= ticketline.product.pricesell %> €</td>
                <td><%= ticketline.units %></td>
              </tr>
              <% end %>
          </tbody>
        </table>
        <div class="text-right">
          <h4>Total : </h4>
          <h3><span id="globalprice"><%= @globalprice %></span> €</h3>
            <%= link_to 'Save', tickets_path, class: 'btn btn-success px-4', data: {method: :post, params: {:id => 2}.to_param} %>
            <%= link_to 'Reset', memory_sale_path(@memory.id), class:'btn btn-danger px-4', data: {method: :delete, params: {:from => 2}.to_param, confirm: 'Delete all products of your list ?'} %>
        </div>
      </div>
    </div>
  </div>

app/views/sales/index.js.erb
var products = document.getElementById('products')
while (products.firstChild) {
    products.removeChild(products.firstChild);
  }
products.insertAdjacentHTML('afterbegin', '<%=j render "card_products", category: Category.find(params[:category_id])%>');

app/views/sales/new.html.erb
<h1 class="h3 mb-2 text-gray-800">Categories</h1>

<div class="row" id="categories">
  <% @categories.each do |category|%>
    <%= render 'card_categories', category: category %>
  <% end %>
</div><h1 class="h3 mb-2 text-gray-800">Categories</h1>

<div id="products">
  <%= render "card_products", category: @category%>
</div>

app/views/sales/new.js.erb
var products = document.getElementById('products')
while (products.firstChild) {
    products.removeChild(products.firstChild);
  }
products.insertAdjacentHTML('afterbegin', '<%=j render "card_products", category: Category.find(params[:category_id])%>');